# This workflow will run on every push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs that will be run
jobs:
  # This is a job with a job ID called "build"
  build:
    # The type of runner that the job will run on
    runs-on: codebuild-github-runner-${{ github.run_id }}-${{ github.run_attempt }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup the desired version of Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm test
